import { Language } from '../models/Language.model';
import { Translations } from '../models/Translation.model';

export const AVAILABLE_LANGUAGES: Language[] = [
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'en', name: 'English', flag: '🇺🇸' }
];

export const TRANSLATIONS: Translations = {
  ru: {
    'products.title': 'Список товаров',
    'products.add': 'Добавить товар',
    'products.details': 'Подробнее',
    'products.addToCart': 'В корзину',
    'products.delete': 'Удалить',
    'products.deleting': 'Удаление...',
    'products.loading': 'Загрузка товаров...',
    'products.retry': 'Попробовать снова',
    'products.notFound': 'По запросу "{query}" ничего не найдено',
    'products.clearSearch': 'Очистить поиск',
    'cart.title': 'Корзина',
    'cart.empty': 'Ваша корзина пуста',
    'cart.total': 'Итого:',
    'cart.clear': 'Очистить корзину',
    'cart.checkout': 'Оформить заказ',
    'cart.goToProducts': 'Перейти к товарам',
    'cart.quantity': 'Количество:',
    'cart.remove': 'Удалить',
    'cart.emptyState': 'Ваша корзина пуста',
    'form.title': 'Форма товара',
    'form.name': 'Название',
    'form.price': 'Цена',
    'form.description': 'Описание',
    'form.category': 'Категория',
    'form.image': 'URL изображения',
    'form.save': 'Сохранить',
    'form.cancel': 'Отмена',
    'form.reset': 'Сбросить',
    'form.required': 'Это поле обязательно для заполнения',
    'form.categoryRequired': 'Пожалуйста, выберите категорию товара',
    'form.imagePattern': 'Введите корректный локальный путь (начинается с /assets/img/) или оставьте поле пустым',
    'common.confirm': 'Вы уверены?',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'product.addedToCart': 'Товар добавлен в корзину!',
    'product.deleteConfirm': 'Вы уверены, что хотите удалить товар "{title}"?',
    'product.backToList': '← Назад к списку',
    'product.edit': 'Редактировать',
    'product.deleteProduct': 'Удалить товар',
    'product.rating': 'Рейтинг: {rate}/5 ({count} отзывов)',
    'product.notFound': 'Товар не найден',
    'category.mouse': 'Мышь',
    'category.keyboard': 'Клавиатура',
    'category.headphones': 'Наушники',
    'category.mousepad': 'Коврик для мыши',
    'description.lunacy-one': 'Lunacy One - это флагманская игровая мышь, которая адаптируется специально под вас. Больше не нужно идти на компромиссы.',
    'description.lunacy-in-space': 'Lunacy In Space - это флагманская клавиатура премиального уровня, в которой продумана каждая мелкая деталь, чтобы игровые сессии даже самых требовательных пользователей проходили с максимальным комфортом. Клавиатура выполнена в формате 98%. Цифровой блок - есть, при этом устройство гораздо аккуратнее и компактнее полноразмерных конкурентов.',
    'description.lunacy-loud': 'Lunacy Loud - это беспроводная гарнитура премиум-класса, разработанная для геймеров, которые привыкли к высочайшему комфорту и качественному звуку.',
    'description.lunacy-night': 'Дарк Проджект x Lunacy Night это не просто красивые наушники. В погоне за красотой мы не забыли и про качество. Прочная алюминиевая рамка гарантирует прочность самой конструкции, а многослойные амбушюры с эффектом памяти и покрытием Ice Silk сделают использование девайса максимально комфортным.',
    'description.lunacy-moonlight': 'Lunacy Moonlight - это самая сбалансированная клавиатура в линейке Lunacy. Проводное подключение и уравновешенный комплект поставки позволили добиться комфортной цены на девайс, сохранив все важнейшие преимущества премиального устройства - невероятно приятный тайпинг, исключительную функциональность и абсолютную надежность',
    'description.lunacy-slip': 'Коврик размера L (50x50 см) предоставляет достаточно места для комфортного размещения мыши. Это позволяет свободно выполнять любые игровые или рабочие действия без ограничений по пространству, повышая удобство и эффективность.',
    'rating.no-rating': 'Нет оценок'
  },
  en: {
    'products.title': 'Products List',
    'products.add': 'Add Product',
    'products.details': 'Details',
    'products.addToCart': 'Add to Cart',
    'products.delete': 'Delete',
    'products.deleting': 'Deleting...',
    'products.loading': 'Loading products...',
    'products.retry': 'Try Again',
    'products.notFound': 'Nothing found for "{query}"',
    'products.clearSearch': 'Clear Search',
    'cart.title': 'Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total:',
    'cart.clear': 'Clear Cart',
    'cart.checkout': 'Checkout',
    'cart.goToProducts': 'Go to Products',
    'cart.quantity': 'Quantity:',
    'cart.remove': 'Remove',
    'cart.emptyState': 'Your cart is empty',
    'form.title': 'Product Form',
    'form.name': 'Name',
    'form.price': 'Price',
    'form.description': 'Description',
    'form.category': 'Category',
    'form.image': 'Image URL',
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'form.reset': 'Reset',
    'form.required': 'This field is required',
    'form.categoryRequired': 'Please select a product category',
    'form.imagePattern': 'Enter a valid local path (starting with /assets/img/) or leave empty',
    'common.confirm': 'Are you sure?',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.error': 'Error',
    'common.success': 'Success',
    'product.addedToCart': 'Product added to cart!',
    'product.deleteConfirm': 'Are you sure you want to delete product "{title}"?',
    'product.backToList': '← Back to list',
    'product.edit': 'Edit',
    'product.deleteProduct': 'Delete Product',
    'product.rating': 'Rating: {rate}/5 ({count} reviews)',
    'product.notFound': 'Product not found',
    'category.mouse': 'Mouse',
    'category.keyboard': 'Keyboard',
    'category.headphones': 'Headphones',
    'category.mousepad': 'Mousepad',
    'description.lunacy-one': 'Lunacy One is a flagship gaming mouse that adapts specifically to you. No more compromises needed.',
    'description.lunacy-in-space': 'Lunacy In Space is a premium flagship keyboard where every small detail is thought out so that gaming sessions of even the most demanding users take place with maximum comfort. The keyboard is made in 98% format. The numeric keypad is present, while the device is much neater and more compact than full-size competitors.',
    'description.lunacy-loud': 'Lunacy Loud is a premium wireless headset designed for gamers who are used to the highest comfort and quality sound.',
    'description.lunacy-night': 'Dark Project x Lunacy Night is not just beautiful headphones. In pursuit of beauty, we did not forget about quality. The durable aluminum frame guarantees the strength of the structure itself, and the multi-layer ear cushions with memory effect and Ice Silk coating will make using the device as comfortable as possible.',
    'description.lunacy-moonlight': 'Lunacy Moonlight is the most balanced keyboard in the Lunacy lineup. Wired connection and balanced delivery kit allowed us to achieve a comfortable price for the device while maintaining all the most important advantages of a premium device - incredibly pleasant typing, exceptional functionality and absolute reliability.',
    'description.lunacy-slip': 'The L-size mat (50x50 cm) provides enough space for comfortable mouse placement. This allows you to freely perform any gaming or work actions without space restrictions, increasing convenience and efficiency.',
    'rating.no-rating': 'No ratings'
  }
};

